### ISSUE TITLE
Double quotes strange behaviour

### ISSUE THREAD

**Issue by fabianosobreira** [textmate/groovy.tmbundle#2]
Editing tags like that

<g:datePicker name="createdAt" precision="day" readeOnly="true" value="${registrationInstance?.createdAt}"  />

in a .gsp page, when I press " (double quotes) i`m getting ${} instead of "".

**Comment by fabianosobreira** [comment]
Actually this is a groovy-grails issue

**Comment by ldaley** [comment]
Grab the latest grails bundle and see if it's fixed.

**Comment by fabianosobreira** [comment]
It`s Fixed. Thank you very much.
