### ISSUE TITLE
CPU Spike on lion

### ISSUE THREAD

**Issue by basejump** [textmate/groovy.tmbundle#6]
Opening this example groovy file in textmate will cause CPU to spike to 100%

class Test {
    def xxx(){
        mc.getEr = {->
        }
    }
}

**Comment by basejump** [comment]
seems to be this
https://github.com/textmate/groovy.tmbundle/commit/128f8dd757287f85d2b725ea6b82cd928673ad6d#L0R486
If I revert back to <string>(?!-&gt;)</string>
then it works fine again in my example above

**Comment by ldaley** [comment]
I can't reproduce this, but I just realised I had unpushed changes.

Can you please confirm that you see the error with the latest master.

**Comment by basejump** [comment]
your last push did the trick. Thanks Luke
I am surprised no one else had this problem. Are we the only ones using mate on Lion?

**Comment by ldaley** [comment]
Unsure, that would be surprising though.
